UsageConfig.py: Convert result map() to list
map() returns iterator instead of list with Python 3.

File "/usr/lib/enigma2/python/Components/UsageConfig.py", line 949, in updateEnterForward
    updateChoices(config.seek.enter_forward, configElement.value)
  File "/usr/lib/enigma2/python/Components/UsageConfig.py", line 1299, in updateChoices
    self.setChoices(map(str, choices), defval)
  File "/usr/lib/enigma2/python/Components/config.py", line 350, in setChoices
    self.choices = choicesList(choices)
  File "/usr/lib/enigma2/python/Components/config.py", line 232, in __init__
    assert False, "choices must be dict or list!"
AssertionError: choices must be dict or list!